; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -I../shared/include

lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    256dpi/MQTT@^2.5.2

[env:esp32-loopback]
extends = env:esp32doit-devkit-v1
build_flags =
    ${env:esp32doit-devkit-v1.build_flags}
    -DSPP_NANO_LOOPBACK=1
    -I../nano/include
extra_scripts = pre:scripts/include-loopback-sources.py
