[platformio]
test_dir = test

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=gnu++17
    -I../shared/include
    -I../esp32/include
    -I../nano/include
extra_scripts = pre:include_sources.py
